#!/usr/bin/env bash
# Script that installs Nginx server, redirects /redirect_me and customizes 404 not found

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=Q7Phkq0BUXM permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/def

sudo service nginx restart
